---

- name: PLAY 01 Upgrade IOS
#  hosts: core
  hosts: jia_c141_620_15
  connection: network_cli
  gather_facts: no

#  roles:
#    - upgrade_ios

  tasks:

    - name: get facts with ios_facts
      ios_facts:
      register: results
#      setup:      
  

    - name: display facts without using roles
      debug:
        var: results
