---

tasks:
    - name: CHECK CURRENT VERSION
      ios_facts:
 
    - debug:
        msg:
        - "Current version is {{ ansible_net_version }}"
        - "Upgrade image is Version 15.2(7)E"
 
    # - debug:
    #     msg:
    #     - "Image is not compliant and will be upgraded"

    - name: Get ansible date/time facts
      setup:
       filter: "ansible_date_time"
       gather_subset: "!all"
 
    - name: Store DTG as fact
      set_fact:
       DTG: "{{ ansible_date_time.date }}"

    - name: Backup Start-up Config to Flash
      ios_command:
       commands: copy start-up "flash:startupB4Upgrade{{ DTG }}"
    

    - name: Copy Running Config to Start-up Config
      ios_command:
       commands: copy run start  
 
      # when: net_version != upgrade_ios_version
